apiVersion: v1
kind: Service
metadata:
  name: km-httpbin
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: km-httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: km-httpbin
spec:
  selector:
    matchLabels:
      app: km-httpbin
  replicas: 1
  template:
    metadata:
      labels:
        app: km-httpbin
    spec:
      containers:
      - name: km-httpbin
        image:rcr.rafay-edge.net/test_prod_org_private/defaultproject/kutumba.manne/km-httpbin:master-c8582f8
        ports:
        - containerPort: 8080
