version: 2
jobs:
  build:
    environment:
          IMAGE_NAME: ${RAFAY_REGISTRY_ENDPOINT}/${RAFAY_ORGANIZATION_LABEL}/httpbin
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          IMAGE_TAG=${CIRCLE_TAG/v/''}
          command: docker build -t $IMAGE_NAME:$IMAGE_TAG .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master

