version: 2
jobs:
    httpbin:
        machine: true
        parameters:
        tag:
                type: string
                default: ${CIRCLE_SHA1}
        dockerfile:
                type: string
                default: Dockerfile
        steps:
                - checkout
                - build:
                        dockerfile: <<parameters.dockerfile>>
workflows:
  version: 2
  build_and_test:
    jobs:
            - httpbin

