version: 2.1
orbs:
  docker: circleci/docker@0.5.13

jobs:
  build-image:
    description: Build a Docker image
    parameters:
      dockerfile:
        type: string
        default: Dockerfile
      extra_build_args:
        type: string
        default: ''
      image_name:
        type: string
      registry:
        type: string
      tag:
        type: string
        default: ${CIRCLE_SHA1}
    steps:
      - checkout
      - docker/build:
          dockerfile: << parameters.dockerfile >>
          image: << parameters.image_name >>
          tag: << parameters.tag >>

workflows:
  version: 2
  build-master:
    jobs:
      - docker/publish:
          deploy: true
          docker-password: $RAFAY_REGISTRY_SECRET
          docker-username: $RAFAY_USERNAME
          dockerfile: Dockerfile
          image: $RAFAY_REGISTRY_ENDPOINT/$RAFAY_ORGANIZATION_LABEL/httpbin
          name: Build httpbin
          registry: $RAFAY_REGISTRY
          tag: ${CIRCLE_SHA1}

