version: 2.1
orbs:
  docker: circleci/docker@0.5.13
  ktest: krao-test/ktest@0.1.13

jobs:
  Publish-Workload:
      machine: true
      steps:
        - checkout
        - ktest/init
        - ktest/add_workload:
              yaml_file: workload.yml
        - ktest/set_workload_image:
              workload: demo-circleci
              container: httpbin
              image: $RAFAY_REGISTRY_ENDPOINT/$RAFAY_ORGANIZATION_LABEL/httpbin
              tag: $CIRCLE_SHA1
        - ktest/publish_workload:
              workload: demo-circleci
        - ktest/check_workload_status:
              workload: demo-circleci
  Test-Workload:
      machine: true
      steps:
        - run:
              name: Test the Workload
              command: |
                sleep 60
                curl -k -v https://demo-circleci.run.rafay-edge.net
  Delete-Workload:
      machine: true
      steps:
        - ktest/init
        - ktest/delete_workload:
            workload: demo-circleci

workflows:
  version: 2
  build-master:
    jobs:
      - docker/publish:
          deploy: true
          docker-password: RAFAY_REGISTRY_SECRET
          docker-username: RAFAY_USERNAME
          dockerfile: Dockerfile
          image: $RAFAY_ORGANIZATION_LABEL/httpbin
          name: Build and push httpbin to Rafay Registry
          registry: $RAFAY_REGISTRY_ENDPOINT
          tag: ${CIRCLE_SHA1}

      - Publish-Workload:
          filters:
            branches:
              only: master
          requires:
            - Build and push httpbin to Rafay Registry
      - Test-Workload:
          requires:
            - Build and push httpbin to Rafay Registry
            - Publish-Workload
      - Delete-Workload:
          requires:
            - Build and push httpbin to Rafay Registry
            - Publish-Workload
            - Test-Workload


