version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            IMAGE_TAG=$CIRCLE_BUILD_NUM
            docker build -t $RAFAY_REGISTRY_ENDPOINT/$RAFAY_ORGANIZATION_LABEL/httpbin:$IMAGE_TAG .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $RAFAY_REGISTRY_ENDPOINT/$RAFAY_ORGANIZATION_LABEL/httpbin
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish:
    executor: docker-publisher
    steps:
     - attach_workspace:
        at: /tmp/workspace
     - setup_remote_docker
     - run:
        name: Load Archived Docker Image
        command: docker load -i /tmp/workspace/image.tar
     - run:
        name: Publish Docker Image to Rafay Registry
        command: |
          echo "$RAFAY_REGISTRY_SECRET" | docker login -u "$RAFAY_USERNAME" --password-stdin $RAFAY_REGISTRY_ENDPOINT
          docker push $RAFAY_REGISTRY_ENDPOINT/$RAFAY_ORGANIZATION_LABEL/httpbin:$IMAGE_TAG

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
