version: 2.1
orbs:
  docker: circleci/docker@0.5.13

workflows:
  version: 2
  build-master:
    jobs:
      - docker/publish:
          deploy: true
          docker-password: $RAFAY_REGISTRY_SECRET
          docker-username: $RAFAY_USERNAME
          dockerfile: Dockerfile
          image: $RAFAY_REGISTRY_ENDPOINT/$RAFAY_ORGANIZATION_LABEL/httpbin
          name: Build httpbin
          registry: $RAFAY_REGISTRY
          tag: ${CIRCLE_SHA1}

