name: ci

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Declare variables for build tag
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_ENDPOINT }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY_ENDPOINT }}/${{ secrets.REGISTRY_LABEL }}/km-httpbin:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
      - 
        name: Set env
        run: echo "IMAGE=${{ secrets.REGISTRY_ENDPOINT }}/${{ secrets.REGISTRY_LABEL }}/km-httpbin:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}" >> $GITHUB_ENV    
      - 
        name: update image in the deployment
        shell: bash
        run: echo $IMAGE
        
      - 
        name: Commit changes
        uses: EndBug/add-and-commit@v6
        with:
          author_name: kutumba
          author_email: nani.36@gmail.com
          message: 'updating image tag'
          add: 'httpbin-deployment.yml'
